import jsPDF from 'jspdf';
import { PatientCase, TreatmentItem, SelectedMedication } from '@/types';
import { format } from 'date-fns';

export class PDFExportService {
  private doc: jsPDF;
  private yPosition: number;
  private pageHeight: number;
  private margin: number;

  constructor() {
    this.doc = new jsPDF();
    this.yPosition = 20;
    this.pageHeight = this.doc.internal.pageSize.height;
    this.margin = 20;
  }

  private checkPageBreak(height: number = 10) {
    if (this.yPosition + height > this.pageHeight - this.margin) {
      this.doc.addPage();
      this.yPosition = 20;
    }
  }

  private addTitle(text: string) {
    this.checkPageBreak(15);
    this.doc.setFontSize(18);
    this.doc.setFont('helvetica', 'bold');
    this.doc.text(text, this.margin, this.yPosition);
    this.yPosition += 15;
  }

  private addSubtitle(text: string) {
    this.checkPageBreak(12);
    this.doc.setFontSize(14);
    this.doc.setFont('helvetica', 'bold');
    this.doc.text(text, this.margin, this.yPosition);
    this.yPosition += 10;
  }

  private addText(text: string, indent: number = 0) {
    this.checkPageBreak(8);
    this.doc.setFontSize(11);
    this.doc.setFont('helvetica', 'normal');
    
    const maxWidth = this.doc.internal.pageSize.width - this.margin * 2 - indent;
    const lines = this.doc.splitTextToSize(text, maxWidth);
    
    lines.forEach((line: string) => {
      this.checkPageBreak(8);
      this.doc.text(line, this.margin + indent, this.yPosition);
      this.yPosition += 7;
    });
  }

  private addBoldText(label: string, value: string, indent: number = 0) {
    this.checkPageBreak(8);
    this.doc.setFontSize(11);
    this.doc.setFont('helvetica', 'bold');
    this.doc.text(label, this.margin + indent, this.yPosition);
    
    this.doc.setFont('helvetica', 'normal');
    const labelWidth = this.doc.getTextWidth(label);
    this.doc.text(value, this.margin + indent + labelWidth + 2, this.yPosition);
    this.yPosition += 8;
  }

  private addDivider() {
    this.checkPageBreak(5);
    this.doc.setDrawColor(200, 200, 200);
    this.doc.line(this.margin, this.yPosition, this.doc.internal.pageSize.width - this.margin, this.yPosition);
    this.yPosition += 10;
  }

  exportInitialClaim(patientCase: PatientCase): void {
    // Header
    this.addTitle('SaluLink Chronic Treatment Claim');
    this.addText(`Generated: ${format(new Date(), 'MMMM dd, yyyy HH:mm')}`);
    this.yPosition += 5;
    this.addDivider();

    // Patient Information
    this.addSubtitle('Patient Information');
    this.addBoldText('Name: ', patientCase.patientName, 5);
    this.addBoldText('Patient ID: ', patientCase.patientId, 5);
    this.addBoldText('Medical Plan: ', patientCase.plan, 5);
    this.yPosition += 5;
    this.addDivider();

    // Clinical Note
    this.addSubtitle('Clinical Note');
    this.addText(patientCase.clinicalNote, 5);
    this.yPosition += 5;
    this.addDivider();

    // Condition & ICD Code
    this.addSubtitle('Diagnosis');
    this.addBoldText('Condition: ', patientCase.condition, 5);
    this.addBoldText('ICD-10 Code: ', patientCase.icdCode, 5);
    this.addText(`Description: ${patientCase.icdDescription}`, 5);
    this.yPosition += 5;
    this.addDivider();

    // Diagnostic Treatments
    if (patientCase.diagnosticTreatments.length > 0) {
      this.addSubtitle('Diagnostic Basket');
      patientCase.diagnosticTreatments.forEach((treatment, index) => {
        this.addText(`${index + 1}. ${treatment.description}`, 5);
        this.addBoldText('  Code: ', treatment.code, 10);
        this.addBoldText('  Times Completed: ', `${treatment.timesCompleted} of ${treatment.maxCovered}`, 10);
        if (treatment.documentation.notes) {
          this.addText(`  Notes: ${treatment.documentation.notes}`, 10);
        }
        this.yPosition += 3;
      });
      this.addDivider();
    }

    // Medications
    if (patientCase.medications.length > 0) {
      this.addSubtitle('Prescribed Medications');
      patientCase.medications.forEach((med, index) => {
        this.addText(`${index + 1}. ${med.medicineNameAndStrength}`, 5);
        this.addText(`   ${med.activeIngredient}`, 10);
        this.addBoldText('   CDA Amount: ', med.cdaAmount, 10);
        this.yPosition += 3;
      });
      
      if (patientCase.medicationNote) {
        this.yPosition += 5;
        this.addText('Registration Note:', 5);
        this.addText(patientCase.medicationNote, 10);
      }
      this.addDivider();
    }

    // Footer
    this.yPosition = this.pageHeight - 30;
    this.doc.setFontSize(9);
    this.doc.setTextColor(150);
    this.doc.text('Generated by SaluLink Chronic Treatment App', this.margin, this.yPosition);
    this.doc.text(`Case ID: ${patientCase.id}`, this.margin, this.yPosition + 5);

    // Save
    this.doc.save(`claim-${patientCase.patientId}-${format(new Date(), 'yyyyMMdd')}.pdf`);
  }

  exportOngoingManagement(patientCase: PatientCase): void {
    // Header
    this.addTitle('Ongoing Management Report');
    this.addText(`Generated: ${format(new Date(), 'MMMM dd, yyyy HH:mm')}`);
    this.yPosition += 5;
    this.addDivider();

    // Patient Information
    this.addSubtitle('Patient Information');
    this.addBoldText('Name: ', patientCase.patientName, 5);
    this.addBoldText('Patient ID: ', patientCase.patientId, 5);
    this.addBoldText('Condition: ', patientCase.condition, 5);
    this.addBoldText('ICD-10: ', patientCase.icdCode, 5);
    this.yPosition += 5;
    this.addDivider();

    // Ongoing Treatments
    if (patientCase.ongoingTreatments.length > 0) {
      this.addSubtitle('Ongoing Management Basket');
      patientCase.ongoingTreatments.forEach((treatment, index) => {
        this.addText(`${index + 1}. ${treatment.description}`, 5);
        this.addBoldText('  Code: ', treatment.code, 10);
        this.addBoldText('  Times Completed: ', `${treatment.timesCompleted} of ${treatment.maxCovered}`, 10);
        if (treatment.documentation.notes) {
          this.addText(`  Notes: ${treatment.documentation.notes}`, 10);
        }
        this.yPosition += 3;
      });
    }

    // Save
    this.doc.save(`ongoing-${patientCase.patientId}-${format(new Date(), 'yyyyMMdd')}.pdf`);
  }

  exportMedicationReport(
    patientCase: PatientCase,
    followUpNotes: string,
    newMedications?: SelectedMedication[],
    motivationLetter?: string
  ): void {
    // Header
    this.addTitle('Medication Report');
    this.addText(`Generated: ${format(new Date(), 'MMMM dd, yyyy HH:mm')}`);
    this.yPosition += 5;
    this.addDivider();

    // Patient Information
    this.addSubtitle('Patient Information');
    this.addBoldText('Name: ', patientCase.patientName, 5);
    this.addBoldText('Patient ID: ', patientCase.patientId, 5);
    this.addBoldText('Condition: ', patientCase.condition, 5);
    this.yPosition += 5;
    this.addDivider();

    // Original Medications
    this.addSubtitle('Current Medications');
    patientCase.medications.forEach((med, index) => {
      this.addText(`${index + 1}. ${med.medicineNameAndStrength}`, 5);
      this.addText(`   ${med.activeIngredient}`, 10);
      this.addBoldText('   CDA Amount: ', med.cdaAmount, 10);
      this.yPosition += 3;
    });
    this.addDivider();

    // Follow-up Notes
    this.addSubtitle('Follow-up Notes');
    this.addText(followUpNotes, 5);
    this.yPosition += 5;
    this.addDivider();

    // New Medications
    if (newMedications && newMedications.length > 0) {
      this.addSubtitle('New Prescribed Medications');
      newMedications.forEach((med, index) => {
        this.addText(`${index + 1}. ${med.medicineNameAndStrength}`, 5);
        this.addText(`   ${med.activeIngredient}`, 10);
        this.addBoldText('   CDA Amount: ', med.cdaAmount, 10);
        this.yPosition += 3;
      });
      this.addDivider();

      if (motivationLetter) {
        this.addSubtitle('Motivation for Medication Change');
        this.addText(motivationLetter, 5);
      }
    }

    // Save
    this.doc.save(`medication-report-${patientCase.patientId}-${format(new Date(), 'yyyyMMdd')}.pdf`);
  }

  exportReferral(
    patientCase: PatientCase,
    urgency: string,
    referralNote: string,
    specialistType: string
  ): void {
    // Header
    this.addTitle('Specialist Referral');
    this.addText(`Generated: ${format(new Date(), 'MMMM dd, yyyy HH:mm')}`);
    this.yPosition += 5;
    
    // Urgency Badge
    this.doc.setFillColor(urgency === 'high' ? 220 : urgency === 'medium' ? 255 : 200, 
                          urgency === 'high' ? 50 : urgency === 'medium' ? 200 : 255, 
                          urgency === 'high' ? 50 : urgency === 'medium' ? 100 : 200);
    this.doc.rect(this.margin, this.yPosition, 40, 8, 'F');
    this.doc.setTextColor(0, 0, 0);
    this.doc.text(`Urgency: ${urgency.toUpperCase()}`, this.margin + 2, this.yPosition + 6);
    this.doc.setTextColor(0, 0, 0);
    this.yPosition += 15;
    this.addDivider();

    // Patient Information
    this.addSubtitle('Patient Information');
    this.addBoldText('Name: ', patientCase.patientName, 5);
    this.addBoldText('Patient ID: ', patientCase.patientId, 5);
    this.addBoldText('Specialist Type: ', specialistType, 5);
    this.yPosition += 5;
    this.addDivider();

    // Diagnosis
    this.addSubtitle('Diagnosis');
    this.addBoldText('Condition: ', patientCase.condition, 5);
    this.addBoldText('ICD-10 Code: ', patientCase.icdCode, 5);
    this.addText(`Description: ${patientCase.icdDescription}`, 5);
    this.yPosition += 5;
    this.addDivider();

    // Case Summary
    this.addSubtitle('Case Summary');
    this.addBoldText('Diagnostic Tests: ', `${patientCase.diagnosticTreatments.length} completed`, 5);
    this.addBoldText('Current Medications: ', `${patientCase.medications.length} prescribed`, 5);
    this.yPosition += 5;
    this.addDivider();

    // Referral Motivation
    this.addSubtitle('Referral Motivation');
    this.addText(referralNote, 5);

    // Save
    this.doc.save(`referral-${patientCase.patientId}-${format(new Date(), 'yyyyMMdd')}.pdf`);
  }
}

